### ISSUE TITLE
Failure on installing glib2 (due to phython dependency problem)

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/glib2#3]
when trying to install "glib2" I get these errors:

ERROR with transaction check vs depsolve:python27.dll wird benötigt von (installiert) python2-rpm-4.13.0-20.oc00.pentium4python27.dll wird benötigt von (installiert) yum-metadata-parser-1.1.4-7.oc00.pentium4python(abi) = 2.7 wird benötigt von python2-pycurl-7.44.1-2.oc00.pentium4python27.dll wird benötigt von python2-pycurl-7.44.1-2.oc00.pentium4python(abi) = 2.7 wird benötigt von (installiert) urlgrabber-3.10.1-10.oc00.noarchpython(abi) = 2.7 wird benötigt von (installiert) python2-rpm-4.13.0-20.oc00.pentium4python(abi) = 2.7 wird benötigt von (installiert) yum-3.4.3-13.oc00.pentium4python(abi) = 2.7 wird benötigt von (installiert) yum-metadata-parser-1.1.4-7.oc00.pentium4python(abi) = 2.7 wird benötigt von (installiert) yum-utils-1.1.31-3.oc00.noarch/@unixroot/usr/bin/python2 wird benötigt von (installiert) cmake-rpm-macros-3.15.3-1.oc00.noarchBitte melden Sie diesen Fehler unter https://github.com/bitwiseworks/rpm-issues

It looks like phyton2 cannot be installed. But "python" as well as "python2-rpm" are already installed on this machine.

**Comment by lerdmann** [comment]
Strange, but reinstalling "python2-rpm" fixed the problem ...

**Comment by SilvanScherrer** [comment]
as it's fixed now, I close the issue. even I have no idea why it failed. The above log doesn't show it.
